### ISSUE TITLE
rtsource/rtsink_conn peername should be stashed in the state so we can give nicer error messages

### ISSUE THREAD

**Issue by bookshelfdave** [basho/riak_repl#247]

**Comment by bowrocker** [comment]
Managed to manually reproduce by:
1. Firewall-ing the cluster-mgr port (10016) from the source
2. This forces a heartbeat timeout on the source end
3. Inserting a inet:close(Socket) before the error logging
4. The logger calls inet:peername() which fails, giving:

erlang.log.2:15:34:04.854 [warning] Realtime connection error:einval to "ec21" heartbeat timeout after 15000 milliseconds

Above, "error:einval" is the error return of inet:peername() when the socket is closed.

The fix is, as the subject reads, to put the peername in the state when the socket is established, so that the logging can still have access to it. 

The problem remains how to test this condition, as just firewalling the port leaves the local (source) socket open.
