### ISSUE TITLE
Handle dead clusterid's for replicated CS manifests

### ISSUE THREAD

**Issue by bookshelfdave** [basho/riak_repl#306]
If a customer disables an entire cluster, how are blocks replicated if manifests have already been replicated with an old clusterid?

Open for discussion.

**Comment by bowrocker** [comment]
Discussed proposed solution with Andrew T:
- Introduce a configuration parameter that maps the current cluster id to one that will serve the blocks after current is disabled. User will configure.
- Mapping will be placed in the ring meta data in riak_repl_ring. 
- riak_repl_pb_get:process/1, which takes a cluster_id, will first check for the mapping, and use the mapped cluster_id if such exists; otherwise it will use the incoming cluster_id

**Comment by bowrocker** [comment]
Closing based on pull requests above.
