### ISSUE TITLE
Integrate repl hook to avoid synchronizing expired objects

### ISSUE THREAD

**Issue by bookshelfdave** [basho/riak_repl#328]
Joe Caswell has worked up a workaround for Netic to avoid synchronizing expired objects. https://gist.github.com/joecaswell/5959715

**Comment by cmeiklejohn** [comment]
Did this get deployed at Netic?

**Comment by cmeiklejohn** [comment]
Moving to 2.1 milestone.

**Comment by engelsanchez** [comment]
If anybody has information on this, let me know. If you see objects that have expired in Bitcask, it's because expiration happened between the time it was fetched and the time it is processed. We have the basic problem of expiration happening at the backend level using the node's local time. Replica repair is unaware of differences between nodes and could possibly resurrect expired objects when there is enough drift to catch them. This hook solution doesn't seem robust enough to implement. I'd rather leave this until a robust Riak wide solution to expiration is developed.  Closing for now. Feel free to add any additional information that may lead to a different conclusion.

**Comment by engelsanchez** [comment]
Actually, leaving duplicate issue #328 open for now and consulting with Mr. Chief Architect about this.
