### ISSUE TITLE
reduced repl mutator issues

### ISSUE THREAD

**Issue by russelldb** [basho/riak_repl#502]
Some things I noticed when trying to solve basho/riak_kv#791
1. Logging - anywhere a local or proxy_get fails needs logging, I commented on the PR about this (basho/riak_repl#402)
2. Stats - whenever there is a `proxy_get` it must be recorded by incrementing stats. If (for some reason) many happen, then the customers will see it in latency stats, corresponding `proxy get` stats would explain it and save CSEs.
3. Proxy Gets - are you sure these should happen anytime except when all replicas agree that M is zero? And even then, isn't once the most we want to do this?
4. Is writing to a key in a reduced-N sink forbidden? Or just inadvisable? This code in riak_kv (https://github.com/basho/riak_kv/blob/develop/src/riak_kv_mutator.erl#L163) means that local siblings from a PUT at the sink may get clobbered completely, or it may mean your mutate_get is never run. Seems wrong. Since you pass the whole object in, why not do a `merge` in `riak_repl_reduced:mutate_get`? We don't want to "lose" data.
5. AAE rehash - in riak_kv_vnode rehash does a local get. Should that get be exactly what is on disk (reduced object (and it's siblings?)) or should it be the mutated_get (this is the question at the heart of basho/riak_kv#791)? If the latter then won't AAE make sure that your reduced N is not reduced anymore?
6. Also part of basho/riak_kv#791 - the `size` warnings from riak_kv on reading large objects, should the `size` be that of the fake on disk locally or mutate_gotten object?
7. Related to 4 above, I see that `aae_hash` is stored in meta, but never used…or not that a grepping can find.

(I might add some more to this as I go)

**Comment by lordnull** [comment]
1: added to list below; cleanest way to do it seems a new pull request.
2: added to list below; I would hope the proxy_get system would keep track of its own stats, but it should be investigated.
3: Proxy_get is currently used as a fallback if anything goes wrong, including local get returning a not found. This does mean it's pretty keen on doing proxy gets. The crux is there
4: added to list below; the pull request https://github.com/basho/riak_kv/pull/801 should handle this but there needs to be more testing.
5, 6, 7: Added to list below. The current plan is to put the aae_hash to use, moving it out of the repl_mutator and into the kv_mutator code path. Have aae check to see if the metadata key is available and use that; if it's not then it does what it always did. The key would be the hash of the object as it was put (before mutators were applied). I don't think it matters if the object used for the hash is the one originally put or the one that is return after mutate_put is applied and used as the return body, though it merits some investigation.

A list for me to keep track of specific tasks.
- [ ] Add logging for failed proxy_gets
- [ ] Whenever there is a proxy_get, the corresponding stats should be incremented; i.e.: don't just assume calling a proxy_get function does this, test it.
- [ ] Ensure keys written to sink cluster do not get clobbered; siblings are preferable to nukes.
- [ ] riak_kv#791 and also put the original object aae_hash in metadata, allowing the aae system to check that rather than needing to go through the entire mutator chain.

**Comment by lordnull** [comment]
Closing for now as mutators have been removed.
